name: Test

on:
  pull_request:
    branches: ["main"]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Run tests
        run: task test

  test-build:
    name: Test Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"

      - name: Install Task
        uses: arduino/setup-task@v2

      - name: Build debug
        run: task build
      - name: Run debug Build
        run: task run -- --help

      - name: Clean
        run: task clean

      - name: Build & Run release Build
        run: task run-release -- --help
